spring.cloud.stream:
  function:
    definition: ordersItalianConsumer;ordersFrenchConsumer;ordersSpanishConsumer
  bindings:
    ordersItalianConsumer-in-0:
      destination: orders-italy-taxed
      content-type: application/json
    ordersFrenchConsumer-in-0:
      destination: orders-french-taxed
      content-type: application/json
    ordersSpanishConsumer-in-0:
      destination: orders-spain-taxed
      content-type: application/json
  kafka:
    binder:
      brokers:
        - localhost:9092
