server:
  port: 8083
spring:
  application:
    name: kstream-producer
  cloud:
    function:
      definition: numberProducer
    stream:
      bindings:
        numberProducer-out-0:
          destination: numbers-test
          producer:
            use-native-encoding: true
      kafka:
        bindings:
          numberProducer-out-0:
            producer:
              configuration:
                value:
                  serializer: org.apache.kafka.common.serialization.LongSerializer
        binder:
          brokers:
          - localhost:9092
