spring.cloud.stream:
  function:
    definition: orderProducer #numberProducer
  bindings:
#    numberProducer-out-0:
#      destination: numbers
#      producer:
#        use-native-encoding: true
    orderProducer-out-0:
      destination: orders
 #     use-native-encoding: true
      content-type: application/json
  kafka:
#    bindings:
#      numberProducer-out-0:
#        producer:
#          configuration:
#            value:
#              serializer: org.apache.kafka.common.serialization.LongSerializer
#      orderProducer-out-0:
#        producer:
#          configuration:
#            value:
#              serializer: org.springframework.kafka.support.serializer.JsonSerializer
#            key:
#              serializer: org.apache.kafka.common.serialization.StringSerializer
    binder:
      brokers:
        - localhost:9092