spring.cloud.stream:
  function:
    definition: orderProducer
  bindings:
    orderProducer-out-0:
      destination: orders
      content-type: application/json
  kafka:
    binder:
      brokers:
        - localhost:9092