spring.cloud.stream:
  function:
    definition: calculateItalianTaxProcessor;calculateFrenchProcessor;calculateSpanishProcessor
  bindings:
    calculateItalianTaxProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateItalianTaxProcessor-out-0:
      destination: orders-italy-taxed
      content-type: application/json
    calculateFrenchProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateFrenchProcessor-out-0:
      destination: orders-french-taxed
      content-type: application/json
    calculateSpanishProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateSpanishProcessor-out-0:
      destination: orders-spain-taxed
      content-type: application/json
  kafka:
    binder:
      brokers:
        - localhost:9092
