spring.cloud.stream:
  function:
    definition: calculateItalianTaxProcessor;calculateFrenchTaxProcessor;calculateSpanishTaxProcessor
  bindings:
    calculateItalianTaxProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateItalianTaxProcessor-out-0:
      destination: orders-italy-taxed
      content-type: application/json
    calculateFrenchTaxProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateFrenchTaxProcessor-out-0:
      destination: orders-french-taxed
      content-type: application/json
    calculateSpanishTaxProcessor-in-0:
      destination: orders
      content-type: application/json
    calculateSpanishTaxProcessor-out-0:
      destination: orders-spain-taxed
      content-type: application/json
  kafka:
    binder:
      brokers:
        - localhost:9092
