spring.cloud.stream:
  function:
    definition: orderItalianProcessor
  bindings:
    orderItalianProcessor-in-0:
      destination: orders
      content-type: application/json
    orderItalianProcessor-out-0:
      destination: orders-italian
      content-type: application/json
  kafka:
    binder:
      brokers:
        - localhost:9092
